version: 0.0
os: linux

files:
  - source: output/index.html #source: 옮길 파일 경로
    destination: /var/www/html/ #옮기는 파일 경로

hooks:
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 300
      runas: root
