version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"

  build:
    commands:
      - echo "Build phase"
      - ls -la          # 현재 디렉토리 파일 목록 확인
      - mkdir -p output
      - cp portal.html output/

      # CodeDeploy 파일 포함
      - cp appspec.yml .
      - mkdir -p scripts
      - cp scripts/restart.sh scripts/

  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  files:
    - appspec.yml
    - output/**/*
    - scripts/**/*
