version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"

  build:
    commands:
      - echo "Build phase - copying file"
      - mkdir output
      - cp Portal.html output/

artifacts:
  files:
    - output/**/*